#DOCS: http://docs.travis-ci.com/user/languages/php/
language: php
php:
  - 7.1

services:
  - mysql

sudo: false

env:
  - CI_ENV=testing

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

matrix:
  fast_finish: true

addons:
  apt:
    packages:
      - oracle-java8-set-default
#  ssh_known_hosts: trackr.moe:22

before_install:
  - travis_retry composer self-update && composer --version #travis is bad at updating composer
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
  #NOTE: Database creation is done in composer.json scripts.

install:
  - composer global require "fxp/composer-asset-plugin:~1.2.2"
  - composer install -n --prefer-dist
  - echo '<?php $db["default"]["username"] = "root"; $db["default"]["password"] = "";' > application/config/testing/database_password.php
  - php public/index.php admin/migrate

before_script:
  # start servers early so they are ready for codecept tests
  - java -jar "vendor/se/selenium-server-standalone/bin/selenium-server-standalone.jar" -port 4444 > /dev/null 2>&1 &
  #BUG: We can't specify CI_ENV normally due to a bug: https://bugs.php.net/bug.php?id=67808
  #     Because of this, we need to edit the index.php.
  - sed -i "1s/.*/<\?php \$_SERVER['CI_ENV'] = 'testing'; \$_SERVER['CI_TESTING'] = 'TRUE';/" public/index.php
  - php -S 127.0.0.1:8000 -t public/ -f index.php > /dev/null 2>&1 &

script:
  #phpunit testing
  - cd application/tests/ && ../../vendor/bin/phpunit --coverage-clover=/tmp/coverage.clover && cd $TRAVIS_BUILD_DIR
  #codeception acceptance testing
  - php vendor/bin/codecept run acceptance --colors

after_success:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover /tmp/coverage.clover

after_failure:
  - cd $TRAVIS_BUILD_DIR && cat application/logs/*
