#DOCS: http://docs.travis-ci.com/user/languages/php/
language: php
php:
  - 7.1

services:
  - mysql

sudo: false

env:
  - CI_ENV=testing

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

matrix:
  fast_finish: true

#addons:
#  ssh_known_hosts: trackr.moe:22

before_install:
  - travis_retry composer self-update && composer --version #travis is bad at updating composer
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
  #NOTE: Database creation is done in composer.json scripts.

install:
  - composer setup-databases
  - composer install -n --prefer-dist
  - echo '<?php $db["default"]["username"] = "root"; $db["default"]["password"] = "";' > application/config/testing/database_password.php
  - php public/index.php admin/migrate

script:
  #phpunit testing
  - cd application/tests/ && ../../vendor/bin/phpunit --coverage-clover=/tmp/coverage.clover --exclude-group SiteTests && cd $TRAVIS_BUILD_DIR
  #codeception acceptance testing
  # FIXME: This in currently on-hold due to a bug with phantomjs freezing. See https://github.com/ariya/phantomjs/issues/14286
  # Also see link for last version of working .travis.yml - https://github.com/DakuTree/manga-tracker/blob/c636bfd728965c2e9bf5890c7b12edc31905a95f/.travis.yml
  #- php vendor/bin/codecept run acceptance --colors

after_success:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover /tmp/coverage.clover

after_script:
  - cd $TRAVIS_BUILD_DIR && cat application/logs/* | egrep -v '^DEBUG.*(Config file loaded|Global POST, GET and COOKIE|No URI present|CI_Session has already|Initialization under CLI|UTF-8 Support Enabled).*'
